### PR TITLE
add a wrapper around extra data

### PR DESCRIPTION
**Pull request by CoderCookE**
This will be used to pass stats for behavioral apps

### CODE REVIEW

**Comment by CoderCookE** [comment]
[ch6225](https://app.clubhouse.io/movableink/story/6225/update-cropduster-library-to-add-sendstats-helper)

**Comment by CoderCookE** [comment]
@mnutt not sure if we want to make this a generic send "state" so they can pass the counter key, I'm also unsure if "position" will help us relink the data back to the block.  If we have a campaign with several block of content and each of those blocks have several behavior apps I don't know if we'd have the context to relink that data back without passing a lot of data in the "position" field.

**Comment by mnutt** [comment]
What do we see `endpoint` being? Ideally it's pretty short...

**Comment by mnutt** [comment]
I think ideally we'd like to figure out a way to leave it open to sending multiple statsdb stats at once. not sure if that looks like one big object with multiple key/value pairs, or an array of key/value pairs.

**Comment by mnutt** [comment]
For instance, `CD.recordStats({'block-1': 1, 'product-12345': 1});` or `CD.recordStats([{key: 'block-1', value: 1}, {key: 'product-12345'}]);`

**Comment by mnutt** [comment]
The advantage of the second one is that I think it's a bit easier to detect in hermes, and allows us to say 'you have a limit of 3 of these' and enforce it.

**Comment by CoderCookE** [comment]
I would imagine, that endpoint would be like endpoint name so likey nothing longer than `most-viewed-products`.  I'm also not sure the value in allowed stats to be sent together, when i think each behavioral app should only display content from a single endpoint.

**Pull request closed without merging**
